### PR TITLE
Fix Open Pyramid Aga 2 Fight

### LINKED ISSUE #421: Soft lock when defeating Aga 2 when open pyramid is selected

### PR DESCRIPTION
**Pull request by MattEqualsCoder**
Closes #421 

Admittedly this is not quite as nice as I would have liked, but it does prevent the soft lock. Basically whenever you enter the Aga 2 fight, it re-closes the pyramid.

### CODE REVIEW

**Review by CPColin — COMMENTED** [review]
I wonder if this introduces a really obscure corner case where somebody starts the Aga2 fight, dies, remembers it's Open Pyramid, quits out of GT, and finds the pyramid closed. I know that's *really* obscure, but is there a way to move the hook to when Aga2 falls down or something?

**Review by Vivelin — APPROVED** [review]

**Comment by MattEqualsCoder** [comment]
> I wonder if this introduces a really obscure corner case where somebody starts the Aga2 fight, dies, remembers it's Open Pyramid, quits out of GT, and finds the pyramid closed. I know that's _really_ obscure, but is there a way to move the hook to when Aga2 falls down or something?

Unfortunately, this is definitely the case. That's why it's definitely not the ideal fix. But, I'm a bit at a loss for how to better fix it with my current expertise.

My main problem is I'm not entirely sure where to hook onto. Here's the ALttP disassembly for Ganon emerging from Aga, which I think we could possibly hook onto:

https://github.com/walkingeyerobot/alttp-disassembly/blob/master/module_ganon_emerges.asm

I think if we were to hook in at the beginning of all this, this could possibly be used, The current randomizer assembly even already hooks in to this. However, that's where things get confusing.

Here's the hook in the randomizer code:

image

And here's the relevant spot in the module_ganon_emerges.asm:

image

Note the line number and command matches, but according to the randomizer it's at address 11E2E but in the disassembly it's between 11F2F - 11F41. I'd try to do some math to calculate some the offset, but there's another spot the randomizer hooks in, and the offsets don't quite match.

Another _possible_ solution could be to just try to flute out if the pyramid is already open, but in the case of open pyramid that means you'd walk in, see Aga, then it would pause to do the whistle and fly away while Aga is just frozen there. Not quite the ideal solution there either.

I'd honestly be curious to see if this is an issue in the Z3 randomizer as well. I don't quite see much that they're doing to prevent this when open pyramid is there. There was some logic that they had, but it seemed to be to prevent fluting away whenever you enter Aga after the pyramid is open (for whatever reason). It didn't seem to help in this situation, though.

**Comment by CPColin** [comment]
Huh, yeah, that offset is weird. Maybe soon I'll roll a 0/0 open pyramid Z3 seed and see if the bug hits them so I can file it (and we can borrow the fix). Makes sense to merge this fix in the meantime.

**Review by CPColin — DISMISSED** [review]

**Comment by MattEqualsCoder** [comment]
Okay, this should be the proper fix now pulled in from ALttPR.

**Pull request merged**
