### PR TITLE
Write rupee count of 2000, little-endian. Closes #330.

### LINKED ISSUE #330: "Fill my rupees" cheat results in a weird value
Looking at `GameService.TryFillRupees()`, the comment says the target value is 2000, but the hex value in the function is 0x1388, which is 5000. Additionally, actually using the cheat results in a displayed value of 4835, suggesting the byte order is wrong (0x8813 is 34835).

We should pick 2000, 5000, or 9999 and get both the comment and the code to agree.

### PR DESCRIPTION
**Pull request by CPColin**

### CODE REVIEW

**Review by MattEqualsCoder — APPROVED** [review]

**Review by Vivelin — DISMISSED** [review]
The absolute cleanest way would probably be to use BitConverter.GetBytes and maybe BitConverter.IsLittleEndian to make sure the order is correct. I don't understand why it's doubled up like this though, maybe that's worth making a comment about?

**Comment by CPColin** [comment]
That's a good question! If I'm reading [this page](http://alttp.run/hacking/index.php?title=SRAM_Map#.24340_to_.2438B_.3D_Items_.26_Equipment) correctly, the first two bytes (at $7ef360) are the wallet capacity and the next two are the rupee count, so maybe we don't actually need to write the first two?

**Comment by CPColin** [comment]
Okay, it looks like if you only write the last two bytes, your rupee count shoots up to 2000 and then starts counting back down to where it was. If you only write the first two bytes, your rupee count starts counting up to 2000. Writing all four bytes sets the count to 2000 and keeps it there, so I'll add a comment to say that.

**Comment by MattEqualsCoder** [comment]
Yeah, I vaguely remember that being confusing to me as well. Wallet capacity on that page is more like your target rupee count and rupee count is just your rupee count that frame. I think there's another value that dictates your max rupee count.

**Comment by CPColin** [comment]
Okay, this version should be much more clear. Thanks for the feedback!

**Review by MattEqualsCoder — APPROVED** [review]

**Pull request merged**
