### PR TITLE
Update rewards to be items

### PR DESCRIPTION
**Pull request by MattEqualsCoder**
This is the first half of the changes to the reward system. This mostly just replaces the previous Reward/RewardItem with ItemType/ItemData, but to the end user everything should function the exact same as today. That being said, I think this will break compatibility with old seed numbers as I no longer shuffle the non-green pendants (honestly not sure why they did that anyway). Saved seeds should be okay though as I added code to be backwards compatible with old reward types.

With these changes, auto tracker should now be able to properly detect red/blue pendants, though.

In the coming days, I'll start working on the actual logic updates.

### CODE REVIEW

**Review by Vivelin — APPROVED** [review]
I sort of looked through everything but honestly I'm pretty tired. I'm not too sure about what this is doing to the code...

**Comment by MattEqualsCoder** [comment]
I'm not in any particular rush or anything if you want to wait to look over it. when you're not tired.

**Comment by Vivelin** [comment]
Nah I just mean I can't really provide better feedback right now than "I'm not sure this feels right"

**Comment by MattEqualsCoder** [comment]
Still, I don't mind giving you some time to mull it over if you're unsure about it.

I went with this way as if we wanted it to work like all other item logic, it would need to be ItemType and Item as that's what the current Progression system is built on. Admittedly the backwards compatibility does become kinda gross, and that's what pains me the most about this solution.

**Comment by Vivelin** [comment]
Couldn't we just add the rewards to the progression/logic?

Well, just an overload for the `canAccess` logic because otherwise that's way too many changes. But y'know.

**Comment by MattEqualsCoder** [comment]
Well, for rom generation we'd need to update the progression to then keep track of both the items and rewards. I can definitely take a look into that if you'd prefer, but that would definitely be more extensive changes unfortunately.

**Comment by MattEqualsCoder** [comment]
Well, maybe not. It'll probably end up requiring a lot of changes to the StandardFiller, but it should be doable.

**Comment by MattEqualsCoder** [comment]
Alright, I think I can probably make it work, but I'll have to make Progression keep both rewards and items. I'll also need to make something equivalent to an Item but for Rewards where they can be matched to a player for multi world.

**Pull request closed without merging**
