### PR TITLE
Keysanity UI and UI Configs

### LINKED ISSUE #33: Better keysanity support in Tracker
It's already possible to track small and big keys, and technically possible to add them to the tracker layout without a code change. This is far from ideal, however.

- A better space-optimized layout for keys might be necessary;
- Separate "playing/tracking logic" from "randomizer logic";
  - The logic only accounts for randomized keys found in chests, not other keys that people playing would probably track;
  - Also makes sense for things like the green pendant and defeating Agahnim.
- Keys in _A Link to the Past_ are straightforward enough. Keycards in Super Metroid, however, were hacked in, and make little sense to most people. 
  - Once a keycard has been tracked, newly unlocked locations should show up on the map. That will already help, but...
  - ...it would be nice to figure out a way to visualize the keycards on the various Super Metroid maps.

### PR DESCRIPTION
**Pull request by MattEqualsCoder**
Closes #33

### CODE REVIEW

**Comment by MattEqualsCoder** [comment]
I haven't actually started the keysanity part, but this basically recreates the functionality of what's already out there using a new config for UIs. Also created a new minimal layout, but I'll include one that's similar to what's out there currently as well.

image

**Comment by Vivelin** [comment]
Looks fine to me so far. We could probably add some keysanity-specific lines for Tracker too now that we have profiles (so Tracker doesn't bother you too much for random keys when you're playing normal mode)

**Comment by MattEqualsCoder** [comment]
Outside of me going through and reviewing/cleaning things up, this should be mostly done. The main new feature I want to add is actually remembering the last used layout. I also want to add more documentation about overwriting sprites and adding new things to the UI.

By default, content will appear as rupees. However, if the BCU profile is on the bottom, his specific images will be used for content. Crocomire will now default to an actual Crocomire picture, but the Sassy profile will override it to the previous stoke image.

**Comment by MattEqualsCoder** [comment]
I still want to review everything to make sure there's nothing I need to clean up, and I'm going to do some additional testing tomorrow, but this now has all functionality and documentation.

**Review by Vivelin — DISMISSED** [review]

**Comment by MattEqualsCoder** [comment]
Okay, I think I'm wrapping a bow on this one. Played for a few hours and found some issues both with these changes and some previous ones made. Also polished a few things up.

**Review by Vivelin — APPROVED** [review]

**Pull request merged**
