### PR TITLE
Adding two Link custom link characters

### PR DESCRIPTION
**Pull request by mcen1**
First one is an original character called Eternal Gamer 81. Second one is the famous Kevin Smith from Smodcast wearing his huge jorts. I made these but largely based them off other Link sprites as templates, such as "Fransen" and "Alice".

### CODE REVIEW

**Comment by MattEqualsCoder** [comment]
Would you be able to adjust the preview pngs? Looks like they're off center to me, and the others are 64x96.

**Comment by mcen1** [comment]
Sure thing, my apologies. Should be all set now.

**Comment by MattEqualsCoder** [comment]
No worries! Those images look better, but I just noticed another thing when I actually pulled it up in SMZ3. The rdc files don't seem to have the metadata attached to them that are used to pull out the sprite names and creator. Admittedly I'm not positive of the normal way of doing this in Sprite Something or any other tool, but I can probably do it for you later today with a tool I have if you send me the display name and creator you'd like displayed in the sprite selector.

**Comment by mcen1** [comment]
Ah, I see. No need for that, I will put them in. Sorry for missing that. One moment...

**Comment by mcen1** [comment]
Ok, the metadata should be in there. Thank you for your patience with me, a first time newbie.

**Comment by MattEqualsCoder** [comment]
Cool, yeah. Looks much better now!
image
Just as a note, you should be able to add spaces to the sprite name. So you should be able to have them as "Eternal Gamer 81" and "Kevin Smith" if you'd like, but it's totally up to you,

**Comment by mcen1** [comment]
Didn't know that, thanks! Added spaces.

**Review by MattEqualsCoder — APPROVED** [review]

**Pull request merged**
